title: Ilse Meyer (UNDER CONSTRUCTION) # your name (or website title) here
logo: "Ilse-Meyer.github.io/images/Ilse_headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  * INPUT INFO HERE *
  <br><br>
  * CURRENT TITLE AND ORGANIZATION * 
  <br><br>
  * PLACE MOTTO HERE *
  <br><br>
  <a href="ILSE RESUME">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/ilsemeyer">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.outstandinginthefield.com/event-details/fruition-farms-creamery">View Fruition Article</a>
  <a href="https://www.places.travel/sections/food/fruition-farm-fruition-restaurant-growing-community">View Travel Article</a>
  <a href="https://www.lifeandthyme.com/food/the-evolving-colorado-cuisine-of-chef-alex-seidel/">View Life and Thyme Article</a>
  <a href="https://www.denverlifemagazine.com/farm-fresh-from-fruition-farms-2-0/">View Denver Life Magazine Article</a>
theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
